### ISSUE TITLE
Add tracing for microprofile-rest-client

### ISSUE THREAD

**Issue by pavolloffay** [eclipse/microprofile-opentracing#82]
Add tracing for https://github.com/eclipse/microprofile-rest-client. Tracing metadata like tags/logs should be the same as for JAX-RS client. 

We need to figure out how this cross-spec specification should be handled. Should it be added here or in microprofile-rest-client? I would vote to add it here. 

cc @pilhuhn @kwsutter 

A pointer to rest-client issue allowing tracing integration https://github.com/eclipse/microprofile-rest-client/issues/35#issuecomment-382441965.

**Comment by pavolloffay** [comment]
Is there any timeline to add MP level spec?

My main concern about adding microprofile-rest-client here is that this spec shouldn't probably directly depend on the `microprofile-rest-client`. What if a vendor does not support mp-rest-client but it wants to use tracing only for jax-rs?

**Comment by andymc12** [comment]
@pavolloffay It should be possible to add Open Tracing providers to the MP Rest Client with only a compile-time dependency on `microprofile-rest-client`.  You would need the compile-time dependency in order to build the `RestClientBuilderListener` implementation class (which could then register the Open Tracing provider(s)), but that class would only be loaded by the MP Rest Client implementation at runtime - so there is no need for a runtime dependency.

**Comment by rafabene** [comment]
[Thorntail 2.3.0.Final documentation](https://docs.thorntail.io/2.3.0.Final/#tracing-a-complex-service_thorntail) mentions this issue. Is there any opened issue on Thorntail for MP-Restclient + MP-Opentracing? It still not working on Thorntail 2.3.0.Final.

The test code is this repo: https://github.com/redhat-developer-demos/microprofile-demo

**Comment by pavolloffay** [comment]
Hi @rafabene, the OT spec supports tracing for MP rest client 1.2. Here is a PR for smallrye https://github.com/smallrye/smallrye-opentracing/pull/28 - at the moment is blocked by not completed rest client implementation. Once smallrye impls are in place it will be used in throntail @kenfinnigan probably knows when that should be.

**Comment by wutingbupt** [comment]
Hi @pavolloffay, I can see the PR is merged, does there is anything new about this request?

**Comment by pavolloffay** [comment]
@wutingbupt the support for MP rest client is supported since 1.2. What else is missing for you?

**Comment by wutingbupt** [comment]
@pavolloffay I have tried this morning with the open tracing 1.3.

But I got something like this:

`{"stackTrace":"java.lang.NoClassDefFoundError: Failed to link io/smallrye/opentracing/SmallRyeRestClientListener (Module \"io.smallrye.opentracing\" from BootModuleLoader@6bb4dd34 for finders [JDK Module Finder, BootstrapClasspathModuleFinder, BootstrapModuleFinder(org.wildfly.swarm.bootstrap), ClasspathModuleFinder, ContainerModuleFinder(swarm.container), ApplicationModuleFinder(thorntail.application), org.wildfly.swarm.bootstrap.modules.DynamicModuleFinder@7d9f158f])
`
I can see the dependency is well added, so I have no idea why it will complain about this .

Br,
Tim

**Comment by pavolloffay** [comment]
@wutingbupt please report this issue in the implementation. This is not related to the specification. So please report this in Smallrye or thorntail depending how you are using it. A dependency tree would be helpful to investigate.

**Comment by wutingbupt** [comment]
Thanks very much, I will do that.

Br,
Tim

Pavol Loffay <notifications@github.com> 于2019年4月15日周一 下午1:06写道：
